[package]
name = "atomic-bridge-counterparty"
version = "1.0.0"
authors = []

[addresses]
MoveBridge = "0x1"
MOVETH = "0x1"
master_minter = "0x1"
minter = "0x1"
pauser = "0x1"
denylister = "0x1"
stablecoin = "0x1"
moveth = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "monza-testing"
subdir = "aptos-move/framework/aptos-framework"

