[package]
name = "atomic-bridge-counterparty"
version = "1.0.0"
authors = []

[addresses]
moveth = "0x1"
master_minter = "0x1"
minter = "0x1"
pauser = "0x1"
denylister = "0x1"

[dev-addresses]
stablecoin = "0xcafe"
master_minter = "0xbab"
minter = "0xface"
pauser = "0xdafe"
denylister = "0xcade"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "1.13.0"
subdir = "aptos-move/framework/aptos-framework"

