[package]
name = "atomic-bridge-counterparty"
version = "1.0.0"
authors = []

[addresses]
MoveBridge = "_"
MOVETH = "_"
master_minter = "_"
minter = "_"
pauser = "_"
denylister = "_"
stablecoin = "_"
moveth = "_"

[dev-addresses]
stablecoin = "0xcafe"
master_minter = "0xbab"
minter = "0xface"
pauser = "0xdafe"
denylister = "0xcade"
moveth = "0xdead"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "1.13.0"
subdir = "aptos-move/framework/aptos-framework"

