[package]
name = "suzuka-client"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = { workspace = true }
aptos-sdk = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
alloy_provider = { workspace = true }
alloy_network = { workspace = true }
alloy_signer_wallet = { workspace = true }
alloy_primitives = { workspace = true }

maptos-execution-util = { workspace = true }
suzuka-executor = { workspace = true }
mcr-settlement-client = { workspace = true }

[lints]
workspace = true
