version: "3"

environment:

processes:

  mcr-client-tests:
    command: |
      set -e
      cargo test -p mcr-settlement-client test_genesis_ceremony -- --nocapture
    depends_on:
      setup:
        condition: process_completed_successfully
    availability:
      # NOTE: `restart: exit_on_failure` is not needed since
      # exit_on_end implies it.
      exit_on_end: true