version: "3"

environment:

processes:

  eth:
    command: |
      mcr-settlement-runner
    depends_on:
      build:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: echo "true"
