version: "3"

environment:

processes:

  monza-client-tests:
    command: |
      # FIXME(nix-ci-fix): this is the latest we can push linking issues, here and in the Monza faucet process we will get a libssl linking issue
      cargo test -p monza-client -- --test-threads=1
    depends_on:
      monza-full-node:
        condition: process_healthy
      monza-faucet:
        condition: process_healthy
    availability:
      exit_on_end: true