version: "3"

environment:

processes:

  monza-client-tests:
    command: |
      ./scripts/services/monza-full-node/client-tests
    depends_on:
      monza-full-node:
        condition: process_healthy
      monza-faucet:
        condition: process_healthy
    availability:
      exit_on_end: true