version: "3"

environment:

processes:

  celestia-node-appd:
    command: |
      m1-da-light-node-celestia-appd
    depends_on:
      setup:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"
    availability:
      restart: exit_on_failure

  celestia-bridge:
    command: |
      m1-da-light-node-celestia-bridge
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"
    depends_on:
       celestia-node-appd:
        condition: process_started
    availability:
      restart: exit_on_failure

  celestia-light-node:
    command: |
      sleep 999999999d
      echo "started"
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: |
          echo "true"
    depends_on:
      celestia-node-appd:
        condition: process_healthy
      celestia-bridge:
        condition: process_healthy