version: "3"

environment:

processes:

  m1-da-light-node-e2e-tests:
    command: |
      ./scripts/services/m1-da-light-node/e2e-tests
    depends_on:
      celestia-light-node: 
        condition: process_healthy
      m1-da-light-node: 
        condition: process_healthy
    availability:
      exit_on_end: true