version: "3"

environment:
  - DOT_MOVEMENT=./.movement
  - CARGO_PROFILE=debug
  - MOVEMENT_PREBUILT=false
  - PATH=$PATH:./target/$CARGO_PROFILE

processes:

  build:
    command: |
      exit 0

  setup:
    command: |
      exit 0
    depends_on:
      build:
        condition: process_completed_successfully

  celestia-light-node:
    command: |
      ./scripts/services/celestia/celestia-local
    readiness_probe:
      exec:
        command: echo "true"
    depends_on:
      setup:
        condition: process_completed_successfully

  celestia-light-node-synced:
    command: |
      ./scripts/services/wait-for-celestia-light-node/run
    depends_on:
      celestia-light-node:
        condition: process_healthy

  m1-da-light-node:
    command: |
      ./scripts/services/m1-da-light-node/run
    depends_on:
      celestia-light-node:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"