version: "3"

environment:
  - DOT_MOVEMENT=./.movement
  - CARGO_PROFILE=debug
  - PATH=$PATH:./target/$CARGO_PROFILE

processes:

  build:
    command: |
      exit 0

  setup:
    command: |
      exit 0

  celestia-light-node:
    command: |
      ./scripts/celestia/celestia-local
    readiness_probe:
      exec:
        command: echo "true"

  celestia-light-node-synced:
    command: |
      cargo run --bin wait-for-celestia-light-node
    depends_on:
      celestia-light-node:
        condition: process_healthy

  m1-da-light-node:
    command: |
      ./target/$CARGO_PROFILE/m1-da-light-node
    depends_on:
      m1-da-light-node-verifier-tests:
        condition: process_completed_successfully
      celestia-light-node:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"