version: "3"

environment:

processes:

  m1-da-light-node:
    command: |
      cargo run -p m1-da-light-node --features "sequencer"
    depends_on:
      m1-da-light-node-verifier-tests:
        condition: process_completed_successfully
      celestia-light-node:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"

  m1-da-light-node-client-tests:
    command: |
      sleep 10
      cargo test -p m1-da-light-node-client --features "sequencer" -- --test-threads=1
    depends_on:
      celestia-light-node: 
        condition: process_healthy
      m1-da-light-node: 
        condition: process_healthy
      m1-da-light-node-verifier-tests:
        condition: process_completed_successfully
