version: "3"

environment:

processes:

  celestia-light-node:
    command: |
      ./scripts/celestia/celestia-local
    readiness_probe:
      exec:
        command: echo "true"

  celestia-light-node-synced:
    command: |
      sleep 10
      cargo run --bin wait-for-celestia-light-node
    depends_on:
      celestia-light-node:
        condition: process_healthy

  m1-da-light-node:
    command: |
      cargo run -p m1-da-light-node
    depends_on:
      m1-da-light-node-verifier-tests:
        condition: process_completed
      celestia-light-node:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"