version: "3"

environment:

processes:

  suzuka-client-tests:
    command: |
      ./scripts/services/suzuka-full-node/client-tests
    depends_on:
      suzuka-full-node:
        condition: process_healthy
      suzuka-faucet:
        condition: process_healthy
    availability:
      exit_on_end: true