version: "3"

environment:

processes:

  build:
    command: |
      exit 0

  setup:
    command: |
      exit 0
    depends_on:
      build:
        condition: process_completed_successfully

  celestia-light-node:
    command: |
      exit 1
    depends_on:
      setup:
        condition: process_completed_successfully

  celestia-light-node-synced:
    command: |
      ./scripts/services/wait-for-celestia-light-node/run
    depends_on:
      celestia-light-node:
        condition: process_healthy

  m1-da-light-node:
    command: |
      ./scripts/services/m1-da-light-node/run
    depends_on:
      celestia-light-node:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"

  suzuka-full-node:
    command: |
      ./scripts/services/suzuka-full-node/run
    depends_on:
      m1-da-light-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"

  suzuka-faucet:
    command : |
      ./scripts/services/suzuka-faucet/run
    depends_on:
      suzuka-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 30
      exec:
        command: echo "true"

