name: Build Push Containers

on:
  push:

jobs:
  containers:
    if: true # Remove this line to enable the job
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        
    runs-on: ${{ matrix.architecture == 'x86_64' && 'movement-runner' || 'buildjet-16vcpu-ubuntu-2204-arm' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3
    - name: Build and Push Docker image movement
      run: |
        ./scripts/movement/build-push-image m1-da-light-node
