name: Checks

on:
  push:

jobs:
  build:
    runs-on: movement-runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Garbage collect nix to help clean build environment
      run: sudo nix-collect-garbage -d

    - name: Run test in nix environment
      run: nix develop --command bash  -c "cargo check"  

    - name: Run test in nix environment
      run: nix develop --command bash  -c "just m1-da-light-node test.local -t=false"  

    - name: Run test in nix environment
      run: nix develop --command bash  -c "just monza-full-node test.local -t=false"  