name: Containers

on:
  push:

jobs:
  containers:

    runs-on: movement-runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker image movement
      run: |
        ./scripts/movement/build-push-image movement
      shell: bash