name: Containers

on:
  push:

jobs:
  m1-da-light-node-builds:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
        
    runs-on: ${{ matrix.architecture == 'x86_64' && 'movement-runner' || 'buildjet-16vcpu-ubuntu-2204-arm' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker image movement
      run: |
        ./scripts/movement/build-push-image m1-da-light-node

  m1-da-light-node-manifest:
    needs: m1-da-light-node-builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image movement
        run: |
          ./scripts/movement/manifest m1-da-light-node
    