name: Container Checks

on:
  workflow_run:
    workflows: ["Build Push Containers"]
    types:
      - completed

jobs:
  container-checks:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
  
      - name: Read the commit SHA
        id: vars
        run: echo "CONTAINER_REV=${{ github.sha }}" >> .env

      - name: Display .env file
        run: cat .env

      - name: Run docker-compose local.setup.test
        run: |
          nix develop --command bash  -c "timeout 5m just suzuka-full-node docker-compose local.setup.test"
