name: Handle Target Comment

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment from issue_comment event'
        required: true
        type: string
      issue_number:
        description: 'Issue number from issue_comment event'
        required: true
        type: string
      html_url:
        description: 'HTML URl from issue_comment event'
        required: true
        type: string

jobs:
  handle-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Output the comment
        run: |
         echo "Comment was: ${{ github.event.inputs.comment }}"
    
  manage-infra-pr:
    if: startsWith(github.event.inputs.comment, 'infra')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract repository name
        id: gali-id
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f2)
          echo "GALI_ID=$REPO_NAME/${{ github.event.inputs.issue_number }}/${{ github.ref_name }}" >> $GITHUB_ENV
          echo "GALI_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Create PR in Infra Repo if not exist
        id: create-new-pr
        uses: ./.github/actions/gali
        with:
          github_token: ${{ secrets.GH_PAT }}
          gali_id: ${{ steps.gali-id.outputs.gali-id }}
          gali_sha: ${{ steps.gali-id.outputs.gali-sha }}
          comment: ${{ github.event.inputs.comment }}
          source_repo: ${{ github.repository }}
          target_repo: 'movementlabsxyz/infra'
